select 1 as column 
select 2 as column 
select 3 as column 
select 4 as column 
select 5 as column 
select 6 as column 
select 7 as column 
select 8 as column 
select 9 as column 
select 10 as column
